name: Reminder for `trunk` PRs

on:
  pull_request:
    branches:
      - trunk

jobs:
  remind-on-trunk-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is targeting `trunk` and add reminder
        uses: actions/github-script@v7
        with:
          script: |
            const prTitle = context.payload.pull_request.title;
            const prNumber = context.payload.pull_request.number;
            const baseBranch = context.payload.pull_request.base.ref;

            if (baseBranch === 'trunk') {
              const body = `⚠️ **Reminder:** Please ensure this code was tested on the \`uat\` branch before merging to \`trunk\`.

🔁 The expected flow is:
1. Merge to \`develop\`
2. Internal testing and approval
3. Merge to \`uat\`
4. Final testing on the UAT site
5. Merge to \`trunk\`

If you haven't tested on \`uat\` yet, please do so before proceeding!`;

              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: prNumber,
                body: body
              });
            }
